name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    
    - name: Checkout submodules
      shell: bash
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git submodule sync --recursive
        git config --global user.name "utkarsh-dixit"
        git config --global user.password "Manudix@1997"
        git -c "http.extraheader=$(git config --local --get http.https://github.com/.extraheader)" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Specify node version
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Use specific Java version for sdkmanager to work
      uses: joschi/setup-jdk@v1
      with:
        java-version: 'openjdk8'
        architecture: 'x64'

    - name: Download Android Emulator Image
      run: |
        echo y | sudo $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-28;google_apis;x86_64" > /dev/null
        $ANDROID_HOME/tools/bin/avdmanager -s create avd -n emu -k "system-images;android-28;google_apis;x86_64" -b "x86_64" -c 1G -d 7 -f

    - name: Install node_modules
      run: |
        yarn install

    - name: Build
      working-directory: android
      run: ./gradlew build
