name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Checkout project
      uses: actions/checkout@v1
      
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
        
    - name: Set git username and email
      run: |
        # 
        git config --global user.email "${GH_USERNAME}@users.noreply.github.com" 
        git config --global user.name "${GH_USERNAME}" 
      env: 
        GH_USERNAME: "utkarsh-dixit"
          
    - name: Checkout submodules
      shell: bash
      run: |
        git config --global url."git@github.com:".insteadOf "https://github.com/"
        git submodule sync --recursive
        git config --global user.name "utkarsh-dixit"
        git -c "http.extraheader=$(git config --local --get http.https://github.com/.extraheader)" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Specify node version
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Use specific Java version for sdkmanager to work
      uses: joschi/setup-jdk@v1
      with:
        java-version: 'openjdk8'
        architecture: 'x64'

    - name: Download Android Emulator Image
      run: |
        echo y | sudo $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-28;google_apis;x86_64" > /dev/null
        $ANDROID_HOME/tools/bin/avdmanager -s create avd -n emu -k "system-images;android-28;google_apis;x86_64" -b "x86_64" -c 1G -d 7 -f

    - name: Install node_modules
      run: |
        yarn install

    - name: Assemble Debug Build
      working-directory: android
      run: ./gradlew assembleDebug
      
    - name: Assemble Release Build
      working-directory: android
      run: ./gradlew assembleRelease

    - uses: actions/upload-artifact@v1
      with:
        name: DEBUG_BUILD
        path: android/app/build/outputs/apk/debug/
        
    - uses: actions/upload-artifact@v1
      with:
        name: RELEASE_BUILD
        path: android/app/build/outputs/apk/release/  
